version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-dev-secret}
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: "/api"
    depends_on:
      - server
    ports:
      - "5173:5173"

volumes:
  postgres_data:
